---
  - hostname: myserver
    ipaddr: 192.168.56.50
    myram: 2048
    cpu: 2
    box: "centos/7"
    hdd_size: "60GB"
    # provision:
    #   - name: 'base'
    #     path: 'base.sh'
    ports: 0
      # - orig_port: 5601
      #   frwd_port: 5601
      # - orig_port: 9200
      #   frwd_port: 9200
      # - orig_port: 9300
      #   frwd_port: 9300
    proxy: 0
      # - http_server: 'url'
      #   https_server: 'url'
      #   noproxy: 'urls'


# new_disks:
  #   - name: mas_1
  #     size: '10 * 1024'
  #     format: VDI